services:
  frontend-dev:
    image: docker.io/library/node:26-slim
    container_name: mercanto-frontend-dev
    working_dir: /app
    volumes:
      - .:/app:z
      - ./node_modules:/app/node_modules:z
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host 0.0.0.0
